name: Release Python SGrCommhandler

on:
  push:
    paths:
      - '.github/workflows/release-commhandler.yml'
      - 'commhandler/**'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to checkout and build'
        required: true
      semver:
        description: 'Package version to deploy'
        required: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    outputs:
      original_tag: ${{ steps.set_tag.outputs.original_tag}}
      semver: ${{ steps.set_tag.outputs.semver}}
    steps:
      - name: Set tag
        id: set_tag
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "Original tag: ${{ github.event.inputs.tag }}"
            TAG="${{ github.event.inputs.tag }}"
          else
            echo "Original tag: ${{ github.event.client_payload.tag }}"
            TAG="${{ github.event.client_payload.tag }}"
          fi
          if [ -z "${{ github.event.inputs.semver }}" ]; then
            if [[ "${TAG}" =~ ^"v" ]]; then
              SEMVER="${TAG:1}"  # This removes the first character, assuming it's 'v'
            else
              SEMVER="${TAG}"
            fi
          else
            SEMVER="${{ github.event.inputs.semver }}"
          fi
          echo "Semver: $SEMVER"
          echo "Tag: $TAG"
          echo "::set-output name=original_tag::$TAG"
          echo "::set-output name=semver::$SEMVER"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel twine setuptools

      - name: Check Python version
        run: |
          python --version

      - name: Checkout SGrPython Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.set_tag.outputs.original_tag }}

      - name: Modify Commhandler Setup File
        if: ${{ steps.set_tag.outputs.semver != '' }}
        working-directory: commhandler
        run: |
          sed -Ei "s/version=\"[^\"]+\",/version=\"${{ steps.set_tag.outputs.semver }}\",/" setup.py
          cat setup.py
          echo "tag = ${{ steps.set_tag.outputs.original_tag }}, semver = ${{ steps.set_tag.outputs.semver }}"

      - name: Install Build Dependencies
        working-directory: commhandler
        run: |
          pip install -r requirements-dev.txt
          pip install -r requirements.txt

      - name: Run Commhandler Tests
        working-directory: commhandler
        run: pytest

      - name: Build Commhandler Package
        id: build
        working-directory: commhandler
        run: python setup.py sdist bdist_wheel

      - name: Publish Commhandler Package to PyPI
        # publish after committing to master or creating tag commhandler-{version}, if output version was defined
        if: (steps.build.outcome == 'success') && (github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/commhandler-')) && (steps.set_tag.outputs.semver != '')
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: commhandler/dist/

      - name: Build Python Docs
        id: pythondoc
        working-directory: commhandler/docs
        run: make html

      - name: Publish Python Docs on Github Pages
        # publish after committing to master or creating tag commhandler-{version}, if output version was defined
        if: (steps.pythondoc.outcome == 'success') && (github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/commhandler-')) && (steps.set_tag.outputs.semver != '')
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Change this if using a different branch
          folder: commhandler/docs/_build/html  # Path where Python docs are generated
          target-folder: docs/commhandler
